'use strict'

/** @type {import('cz-git').UserConfig} */
module.exports = {
  messages: {
    type: 'Select the type of change:',
    scope: 'Which scope is affected? (optional)',
    customScope: 'Specify a custom scope:',
    subject: 'Short, imperative description (max 50 chars):\n',
    body: "Longer description (optional). Use '|' for line breaks:\n",
    breaking: 'BREAKING CHANGE description (be explicit — this bumps the major version):\n',
    footerPrefixesSelect: 'Related issues (optional):',
    customFooterPrefix: 'Custom footer prefix:',
    footer: 'Issue references (e.g. #31, #34):\n',
    confirmCommit: 'Confirm this commit?',
  },
  types: [
    { value: 'feat',     name: '✨ feat:      A new feature',                         emoji: ':sparkles:' },
    { value: 'fix',      name: '🐛 fix:       A bug fix',                             emoji: ':bug:' },
    { value: 'docs',     name: '📝 docs:      Documentation only',                    emoji: ':memo:' },
    { value: 'style',    name: '💄 style:     Formatting, no functional change',      emoji: ':lipstick:' },
    { value: 'refactor', name: '♻️  refactor:  Code restructure without fix or feat', emoji: ':recycle:' },
    { value: 'perf',     name: '⚡️ perf:      Performance improvement',              emoji: ':zap:' },
    { value: 'test',     name: '✅ test:      Add or fix tests',                      emoji: ':white_check_mark:' },
    { value: 'build',    name: '📦 build:     Build system or external dependencies', emoji: ':package:' },
    { value: 'ci',       name: '👷 ci:        CI/CD configuration',                   emoji: ':construction_worker:' },
    { value: 'chore',    name: '🔧 chore:     Tooling, config, maintenance',          emoji: ':wrench:' },
    { value: 'security', name: '🔒 security:  Security fix or hardening',             emoji: ':lock:' },
    { value: 'revert',   name: '⏪ revert:    Revert a previous commit',              emoji: ':rewind:' },
    { value: 'wip',      name: '🚧 wip:       Work in progress (do not merge)',       emoji: ':construction:' },
  ],
  useEmoji: true,
  emojiAlign: 'left',
  useAI: false,
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  allowBreakingChanges: ['feat', 'fix', 'refactor'],
  skipQuestions: ['footer'],
  upperCaseSubject: false,
  markBreakingChangeMode: true,
  breaklineNumber: 100,
  breaklineChar: '|',
  minSubjectLength: 3,
  maxSubjectLength: 50,
  confirmColorize: true,
  issuePrefixes: [
    { value: 'close', name: 'close:  close an issue on merge' },
    { value: 'fix',   name: 'fix:    fix and close on merge' },
    { value: 'ref',   name: 'ref:    reference without closing' },
  ],
  defaultIssuesPrefixs: 'close',
}
