name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  dependency-review:
    name: Review dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Dependency Review
        uses: actions/dependency-review-action@da43e2d33d1c17d2a26ac1c71cd8a84e95f3c873 # v4.7.1
        with:
          fail-on-severity: high
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-3.0
